### ISSUE TITLE
Duplicating Action does not update parameters

### ISSUE THREAD

**Issue by MikalDev** [armandoalonso/c3IDE#12]
When duplicating action on action tab, all action parameters/json/ace/scriptname remain the same as the action being duplicated. Can some of the parameters be updated based on the new action ID, similar to how duplicate condition or expression works?

**Comment by armandoalonso** [comment]
question, before you duplicated the action did you modify the id? after looking at the code, duplicating the addon only changes the id for ace/lang/code and it also updates the script name. all other text should have been copied

**Comment by MikalDev** [comment]
Let's close this for now, I've had conflicting experience, recently has been working, could have been user error.
