### ISSUE TITLE
add async flag for actions

### ISSUE THREAD

**Issue by armandoalonso** [armandoalonso/c3IDE#13]
this will generate an async function for the action when compiled.

**Comment by armandoalonso** [comment]
this is implemented for the next build

**Comment by armandoalonso** [comment]
there is also a very simple work around just add async keyword in code window in front of the action script name.
![image](https://user-images.githubusercontent.com/7579560/53533393-ba00de00-3ac8-11e9-9c4a-9ec228ec0970.png)

**Comment by MikalDev** [comment]
Looks good.

**Comment by armandoalonso** [comment]
this fix has been deployed
