### ISSUE TITLE
Feature request: allow non-js to be included for 3rd party files

### ISSUE THREAD

**Issue by MikalDev** [armandoalonso/c3IDE#14]
Allow non javascript files to be included as 3rd party files.

This came up with the greenworks addon, where I need to include *.node binary files. Right now I need to add pointers inside addon.json and plugin.js, then after building *.c3addon, need to open that up and add the files manually.

It may be difficult to automatically add the addon.json and plugin.js, but that's ok, more important is to have the files be included in *.c3addon (or in local server dir for dev testing)

**Comment by armandoalonso** [comment]
there is nothing stopping you from any adding file type, using drag and drop. click the add new file will always default to text file (js, css, html) but you can drag and drop binary files the content won't be readable but they will get packaged up in the c3addon file.

the question is a matter of placement right now all files are going into the runtime folder. i can make it so so all non standard files get placed in root of c3addon and all js gets placed in c3 runtime. how would you envision the feature working?

**Comment by armandoalonso** [comment]
the question is a matter of placement right now all files are going into the runtime folder. i can make it so so all non standard files get placed in root of c3addon and all js gets placed in c3 runtime. how would you envision the feature working? would you want to option to choose where the file gets placed? should i separate those 2 concepts attaching javascript to be run as part of the addon and have a seperate tab for attachments? where you can all all types of non text files to be bundled into the addon but not really included? for the case of the node binary did you have to also add a reference to that file in the addon json?

**Comment by MikalDev** [comment]
I was Doing It Wrong - I think I was dragging from the contents of a zip file and that did not work. Using the uncompressed version of the folder and it worked, my fault. I think it can work as it is, checking now.

**Comment by MikalDev** [comment]
I tried it out, I see two issues: the exported *.c3ide file grew by 5X what I expected based on the size of the binary files. When I created the c3addon and checked the contents, the binary files looked to about 2X what I expected. To try, just add a binary file, export check size of *c3IDE, then create c3addon, unzip and check the size of the binary file in c3addon.

**Comment by armandoalonso** [comment]
okay i see whats happening, i will fix this. so putting those files in the runtime folder is the correct place?

**Comment by MikalDev** [comment]
For these particular files, the best place would be in the top level directory. In this case if this did support C2 and C3 runtimes, both runtimes would use the same files.

**Comment by armandoalonso** [comment]
this feature will be in the next release, i fixed the bug with non text files duplicating in size, so as of now it will accept any files, and it compiles them based on their extension. so if it's a js ,css,html,json,xml,txt it will be sent to the c3runtime folder all other files get put on the root of the c3addon .

**Comment by MikalDev** [comment]
With new release.

Trying to add binary 3rd party files on compile I get 3/18/2019 9:43:18 PM : Info => error => Value cannot be null.
Parameter name: bytes

**Comment by armandoalonso** [comment]
okay found the issue, i added a new property to the third party addon model, but i did not add a fallback if that property is null. so the c3ide file does not contain the new property it causes this error on compile, i am currently fixing. i should be deploying a new version later today. with this and a few other tweaks

**Comment by armandoalonso** [comment]
this fix has been deployed
