### ISSUE TITLE
Program stopped working on first run

### ISSUE THREAD

**Issue by tatosgames** [armandoalonso/c3IDE#17]
On a fresh installation the program doesn't run, in event log I have this report.
I may suggest to check prerequisite on deploy? (maybe is missing some runtime.dll that can be includable in deploy)

Or use the "copylocal" from visualstudio https://stackoverflow.com/questions/3167395/visual-studio-copy-local

`Version=1
EventType=CLR20r3
EventTime=131986769966498801
ReportType=2
Consent=1
UploadTime=131986769969885194
ReportStatus=268435456
ReportIdentifier=de3fa80b-8c3f-4195-a7f1-0f007880d1b0
IntegratorReportIdentifier=0b0be64c-0685-4d70-bd05-6a0ab988d180
Wow64Host=34404
Wow64Guest=332
NsAppName=c3IDE.exe
OriginalFilename=c3IDE.exe
AppSessionGuid=00001bac-0001-0003-0b3a-a29a44e9d401
TargetAppId=W:00064d64c57851200787c5355137089478b600000000!00000d828cd65b2bc9659fa9558ba582357e32703eb8!c3IDE.exe
TargetAppVer=2019//04//02:10:57:04!0!c3IDE.exe
BootId=4294967295
TargetAsId=1654
IsFatal=1
EtwNonCollectReason=1
Response.BucketId=0ce12cbbb68c9b708495679a5fa79239
Response.BucketTable=5
Response.LegacyBucketId=1483205565015888441
Response.type=4
Sig[0].Name=Problem Signature 01
Sig[0].Value=c3IDE.exe
Sig[1].Name=Problem Signature 02
Sig[1].Value=1.0.0.0
Sig[2].Name=Problem Signature 03
Sig[2].Value=5ca34000
Sig[3].Name=Problem Signature 04
Sig[3].Value=c3IDE
Sig[4].Name=Problem Signature 05
Sig[4].Value=1.0.0.0
Sig[5].Name=Problem Signature 06
Sig[5].Value=5ca34000
Sig[6].Name=Problem Signature 07
Sig[6].Value=3
Sig[7].Name=Problem Signature 08
Sig[7].Value=153
Sig[8].Name=Problem Signature 09
Sig[8].Value=System.NullReferenceException
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=10.0.17763.2.0.0.256.49
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1040
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=2beb
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=2beba6fb4680d73a8c78ca7c24ccdb46
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=900a
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=900ace4b71a5dd638cea219188cb9500
UI[2]=C:\Users\tatog\AppData\Local\Apps\2.0\V59LW0BZ.7AX\QQD1LOPG.CE3\c3id..tion_0000000000000000_0001.0001_898ed2bf74a0b85b\c3IDE.exe
LoadedModule[0]=C:\Users\tatog\AppData\Local\Apps\2.0\V59LW0BZ.7AX\QQD1LOPG.CE3\c3id..tion_0000000000000000_0001.0001_898ed2bf74a0b85b\c3IDE.exe
LoadedModule[1]=C:\WINDOWS\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\WINDOWS\SYSTEM32\MSCOREE.DLL
LoadedModule[3]=C:\WINDOWS\System32\KERNEL32.dll
LoadedModule[4]=C:\WINDOWS\System32\KERNELBASE.dll
LoadedModule[5]=C:\WINDOWS\SYSTEM32\apphelp.dll
LoadedModule[6]=C:\WINDOWS\System32\ADVAPI32.dll
LoadedModule[7]=C:\WINDOWS\System32\msvcrt.dll
LoadedModule[8]=C:\WINDOWS\System32\sechost.dll
LoadedModule[9]=C:\WINDOWS\System32\RPCRT4.dll
LoadedModule[10]=C:\WINDOWS\System32\SspiCli.dll
LoadedModule[11]=C:\WINDOWS\System32\CRYPTBASE.dll
LoadedModule[12]=C:\WINDOWS\System32\bcryptPrimitives.dll
LoadedModule[13]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\mscoreei.dll
LoadedModule[14]=C:\WINDOWS\System32\SHLWAPI.dll
LoadedModule[15]=C:\WINDOWS\System32\combase.dll
LoadedModule[16]=C:\WINDOWS\System32\ucrtbase.dll
LoadedModule[17]=C:\WINDOWS\System32\GDI32.dll
LoadedModule[18]=C:\WINDOWS\System32\gdi32full.dll
LoadedModule[19]=C:\WINDOWS\System32\msvcp_win.dll
LoadedModule[20]=C:\WINDOWS\System32\USER32.dll
LoadedModule[21]=C:\WINDOWS\System32\win32u.dll
LoadedModule[22]=C:\WINDOWS\System32\IMM32.DLL
LoadedModule[23]=C:\WINDOWS\System32\kernel.appcore.dll
LoadedModule[24]=C:\WINDOWS\SYSTEM32\VERSION.dll
LoadedModule[25]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
LoadedModule[26]=C:\WINDOWS\SYSTEM32\MSVCR120_CLR0400.dll
LoadedModule[27]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\mscorlib\e8980cc30db74aebb06ed60c8b93c295\mscorlib.ni.dll
LoadedModule[28]=C:\WINDOWS\System32\ole32.dll
LoadedModule[29]=C:\WINDOWS\system32\uxtheme.dll
LoadedModule[30]=C:\WINDOWS\SYSTEM32\dfshim.dll
LoadedModule[31]=C:\WINDOWS\System32\SHELL32.dll
LoadedModule[32]=C:\WINDOWS\System32\cfgmgr32.dll
LoadedModule[33]=C:\WINDOWS\System32\shcore.dll
LoadedModule[34]=C:\WINDOWS\System32\windows.storage.dll
LoadedModule[35]=C:\WINDOWS\System32\profapi.dll
LoadedModule[36]=C:\WINDOWS\System32\powrprof.dll
LoadedModule[37]=C:\WINDOWS\System32\cryptsp.dll
LoadedModule[38]=C:\WINDOWS\SYSTEM32\urlmon.dll
LoadedModule[39]=C:\WINDOWS\SYSTEM32\iertutil.dll
LoadedModule[40]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System\8947a8d55395210977193e7a23b68487\System.ni.dll
LoadedModule[41]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Core\74a39ac3fa527e9b29393d06faa48d5e\System.Core.ni.dll
LoadedModule[42]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\WindowsBase\61e1779c510ae6dc9fd7133be1146072\WindowsBase.ni.dll
LoadedModule[43]=C:\WINDOWS\system32\rsaenh.dll
LoadedModule[44]=C:\WINDOWS\System32\bcrypt.dll
LoadedModule[45]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\PresentationCore\12e53745e4279de01ca21c9f01355f8b\PresentationCore.ni.dll
LoadedModule[46]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\Presentatio5ae0f00f#\e85f4172e1ee38a7f7c252c3c289fb11\PresentationFramework.ni.dll
LoadedModule[47]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xaml\9b7d06bdaea2097ad9255fd4aff112c1\System.Xaml.ni.dll
LoadedModule[48]=C:\WINDOWS\SYSTEM32\dwrite.dll
LoadedModule[49]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\wpfgfx_v0400.dll
LoadedModule[50]=C:\WINDOWS\System32\OLEAUT32.dll
LoadedModule[51]=C:\WINDOWS\SYSTEM32\MSVCP120_CLR0400.dll
LoadedModule[52]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\WPF\PresentationNative_v0400.dll
LoadedModule[53]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\clrjit.dll
LoadedModule[54]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Configuration\8170dc7f2a919b014ab07c58310fed8b\System.Configuration.ni.dll
LoadedModule[55]=C:\WINDOWS\assembly\NativeImages_v4.0.30319_32\System.Xml\19712ae056bf81cb80aaa60dcf56ebae\System.Xml.ni.dll
LoadedModule[56]=C:\WINDOWS\system32\dwmapi.dll
LoadedModule[57]=C:\WINDOWS\System32\CRYPT32.dll
LoadedModule[58]=C:\WINDOWS\System32\MSASN1.dll
LoadedModule[59]=C:\Windows\Microsoft.NET\Framework\v4.0.30319\diasymreader.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
OsInfo[0].Key=vermaj
OsInfo[0].Value=10
OsInfo[1].Key=vermin
OsInfo[1].Value=0
OsInfo[2].Key=verbld
OsInfo[2].Value=17763
OsInfo[3].Key=ubr
OsInfo[3].Value=379
OsInfo[4].Key=versp
OsInfo[4].Value=0
OsInfo[5].Key=arch
OsInfo[5].Value=9
OsInfo[6].Key=lcid
OsInfo[6].Value=1040
OsInfo[7].Key=geoid
OsInfo[7].Value=118
OsInfo[8].Key=sku
OsInfo[8].Value=49
OsInfo[9].Key=domain
OsInfo[9].Value=0
OsInfo[10].Key=prodsuite
OsInfo[10].Value=256
OsInfo[11].Key=ntprodtype
OsInfo[11].Value=1
OsInfo[12].Key=platid
OsInfo[12].Value=10
OsInfo[13].Key=sr
OsInfo[13].Value=0
OsInfo[14].Key=tmsi
OsInfo[14].Value=1376
OsInfo[15].Key=osinsty
OsInfo[15].Value=3
OsInfo[16].Key=iever
OsInfo[16].Value=11.379.17763.0-11.0.115
OsInfo[17].Key=portos
OsInfo[17].Value=0
OsInfo[18].Key=ram
OsInfo[18].Value=8094
OsInfo[19].Key=svolsz
OsInfo[19].Value=475
OsInfo[20].Key=wimbt
OsInfo[20].Value=0
OsInfo[21].Key=blddt
OsInfo[21].Value=180914
OsInfo[22].Key=bldtm
OsInfo[22].Value=1434
OsInfo[23].Key=bldbrch
OsInfo[23].Value=rs5_release
OsInfo[24].Key=bldchk
OsInfo[24].Value=0
OsInfo[25].Key=wpvermaj
OsInfo[25].Value=0
OsInfo[26].Key=wpvermin
OsInfo[26].Value=0
OsInfo[27].Key=wpbuildmaj
OsInfo[27].Value=0
OsInfo[28].Key=wpbuildmin
OsInfo[28].Value=0
OsInfo[29].Key=osver
OsInfo[29].Value=10.0.17763.379.amd64fre.rs5_release.180914-1434
OsInfo[30].Key=buildflightid
OsInfo[30].Value=82DD3C30-D6F9-4FB5-94E9-3B896CFC20C2.1
OsInfo[31].Key=edition
OsInfo[31].Value=ProfessionalN
OsInfo[32].Key=ring
OsInfo[33].Key=expid
OsInfo[34].Key=containerid
OsInfo[35].Key=containertype
OsInfo[36].Key=edu
OsInfo[36].Value=0
FriendlyEventName=Stopped working
ConsentKey=CLR20r3
AppName=c3IDE
AppPath=C:\Users\tatog\AppData\Local\Apps\2.0\V59LW0BZ.7AX\QQD1LOPG.CE3\c3id..tion_0000000000000000_0001.0001_898ed2bf74a0b85b\c3IDE.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=903D17A233AE7A0F76332E51EF9E63E7
MetadataHash=1091997633`

**Comment by armandoalonso** [comment]
okay, i have identified and fix the issue. the issue was not a missing dll it was a null reference at the start of the application associated with the user defined  options. this has been fixed and should now work for all new installation.

**Comment by tatosgames** [comment]
Thank you!
