### ISSUE TITLE
Crashes on change addon-id

### ISSUE THREAD

**Issue by masscube** [armandoalonso/c3IDE#20]
When i "change the addon-id" and click then on replace -> the tool crashes with this error-message:

> There was an unhandled error in the application. see logs below => 
> ERROR MESSAGE => Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
> ERROR TRACE =>    bei System.Collections.Generic.Dictionary`2.get_Item(TKey key)
>    bei c3IDE.Utilities.Search.Searcher.ReconstructAdoon(C3Addon addon)
>    bei c3IDE.Utilities.Search.Searcher.GlobalReplace(C3Addon addon, IEnumerable`1 replaceResults)
>    bei c3IDE.Windows.SearchAndReplaceWindow.ReplaceAllSelected_Click(Object sender, RoutedEventArgs e)
>    bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs e)
>    bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
>    bei System.Windows.Controls.Button.OnClick()
>    bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
>    bei System.Windows.UIElement.OnMouseLeftButtonUpThunk(Object sender, MouseButtonEventArgs e)
>    bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
>    bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
>    bei System.Windows.Input.MouseButtonEventArgs.InvokeEventHandler(Delegate genericHandler, Object genericTarget)
>    bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
>    bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
>    bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
>    bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
>    bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
>    bei System.Windows.UIElement.RaiseEvent(RoutedEventArgs args, Boolean trusted)
>    bei System.Windows.Input.InputManager.ProcessStagingArea()
>    bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
>    bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
>    bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
>    bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
>    bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
>    bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
>    bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
> ERROR INNER EX => 
> ERROR SOURCE => mscorlib
> 
> EXCEPTION LIST =>

**Comment by armandoalonso** [comment]
would you mind attaching the project file to debug through the issue.

**Comment by armandoalonso** [comment]
located issue, caused by new addition of c2runtime file, not being index by search system. should be working now
