### ISSUE TITLE
Bool not highlighted for effects

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#29]
boolean is highlighted though, which is not a known GLSL type

![image](https://user-images.githubusercontent.com/11213825/57015106-f527a680-6c0a-11e9-8e64-701ddc4c2911.png)

**Comment by armandoalonso** [comment]
this should be a quick fix, i can have it out later today

**Comment by armandoalonso** [comment]
this has been deployed in v1.1.0.55
