### ISSUE TITLE
Generate uniforms always add them on top of main

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#30]
This can be an issue when you have any other function that needs to be on top of main as well, the uniforms end up getting added between the two

![image](https://user-images.githubusercontent.com/11213825/57015159-2ef8ad00-6c0b-11e9-9184-68c8d206ad1e.png)

**Comment by armandoalonso** [comment]
this should be a quick fix, i can have it out later today

**Comment by armandoalonso** [comment]
this has been deployed in v1.1.0.55
