### ISSUE TITLE
Fix on click "Add new action" app crash

### ISSUE THREAD

**Issue by hermannvincent** [armandoalonso/c3IDE#38]
Hello so i have c3IDE crashing when i click on Add new action.

I tried to reinstall, but the bug still there and i don't get a log. Just a loading mouse cursor hover the Add new button.

In the image you can't see my mouse loading cursor and i don't know why.

![image](https://user-images.githubusercontent.com/51874197/59908786-0dbe6c80-93c3-11e9-84c5-135808b6ea3c.png)

**Comment by armandoalonso** [comment]
is it possible for you to share you project file? that will help me debug the issue. without the error log. it much harder to try and in point the issue. if you dont want to attach it here. you can send it to me armandoalonso1@gmail.com

**Comment by armandoalonso** [comment]
also could you try to right click in the action section, and click on "Add New Action" and see if you get the same crash? Whats about Conditions? and Expression do they also fail. without the actual error, and no project file. it really hard to figure out the root cause of the issue.

**Comment by hermannvincent** [comment]
It's only when i get the "Add new action" button then i got the c3ide
window is not responding, the others like conditions and expression work as
well.
My current setup is Window 10 arch 86-64

Le ven. 21 juin 2019 à 02:23, armando alonso <notifications@github.com> a
écrit :

**Comment by armandoalonso** [comment]
i can't seem to reproduce this issue, if you could provide the project file file, i might be able to debug it. i have been able to add new action. in order to figure this one out we need to determine if it's the project configuration, or maybe the app data got corrupt on your system. have you tried opening the program as an administrator (this should not be needed) but its worth a try.

**Comment by skymen** [comment]
Closed for inactivity. If the issue persists, please open a new issue
