### ISSUE TITLE
No "collapse code" in c2runtime tab

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#39]
There is no collapse code in there :(
![image](https://user-images.githubusercontent.com/11213825/60216149-94fb5c80-9869-11e9-91b9-f5b08bfc71fb.png)

**Comment by armandoalonso** [comment]
yeah i stay away from the c2 file on purpose, i never meant for this ide to be a c2 addon ide. the file only gets looked at for searching now, and during import for the conversion. i can go ahead and work on adding the folding there it should be pretty simple. but i don't plan on adding code completion in this file.

**Comment by skymen** [comment]
Yeah no need for code completion, I just fold stuff I'm done with, makes it easier to read

**Comment by armandoalonso** [comment]
okay cool i should be done adding it in a day or two, when i get a bit time

**Comment by skymen** [comment]
Great 👌

**Comment by armandoalonso** [comment]
i have added code folding to c2 runtime in latest build
