### ISSUE TITLE
Error generating 3rd party files

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#40]
I don't really know why this happens, so this is more of a request for help
<details><summary>Error</summary>

27/06/2019 02:28:14 : Info => compilation starting...
27/06/2019 02:28:14 : Info => compile directory exists => C:\Users\ossam\AppData\Roaming\C3IDE_DATA\Server\Test\airconsole
27/06/2019 02:28:14 : Info => removed compile directory...
27/06/2019 02:28:14 : Info => recreating compile directory => C:\Users\ossam\AppData\Roaming\C3IDE_DATA\Server\Test\airconsole
27/06/2019 02:28:14 : Info => compile directory created successfully => C:\Users\ossam\AppData\Roaming\C3IDE_DATA\Server\Test\airconsole
27/06/2019 02:28:14 : Info => generating addon.json
27/06/2019 02:28:14 : Info => generating addon.json => complete
27/06/2019 02:28:14 : Info => generating plugin.js (edittime)
27/06/2019 02:28:14 : Info => generating plugin.js (edittime) => complete
27/06/2019 02:28:14 : Info => generating plugin.js (runtime)
27/06/2019 02:28:14 : Info => generating plugin.js (runtime) => complete
27/06/2019 02:28:14 : Info => generating type.js (edittime)
27/06/2019 02:28:14 : Info => generating type.js (edittime) => complete
27/06/2019 02:28:14 : Info => generating instance.js (edittime)
27/06/2019 02:28:14 : Info => generating instance.js (edittime) => complete
27/06/2019 02:28:14 : Info => generating ace.json
27/06/2019 02:28:14 : Info => generating ace.json => complete
27/06/2019 02:28:14 : Info => generating en-US.json
27/06/2019 02:28:14 : Info => generating en-US.json => complete
27/06/2019 02:28:14 : Info => generating type.js (runtime)
27/06/2019 02:28:14 : Info => generating type.js (runtime) => complete
27/06/2019 02:28:14 : Info => generating instance.js (runtime)
27/06/2019 02:28:14 : Info => generating instance.js (runtime) => complete
27/06/2019 02:28:14 : Info => generating action.js
27/06/2019 02:28:14 : Info => generating action.js => complete
27/06/2019 02:28:14 : Info => generating conditions.js
27/06/2019 02:28:14 : Info => generating conditions.js => complete
27/06/2019 02:28:14 : Info => generating expressions.js
27/06/2019 02:28:14 : Info => generating expressions.js => complete
27/06/2019 02:28:14 : Info => generating 3rd party files
27/06/2019 02:28:14 : Info => compilation terminated due to error...
27/06/2019 02:28:14 : Info => error => The value cannot be null.
Name of the parameter : bytes

</details>

I'm trying to compile this project:
[Psychokiller1888 for N-Dream AG_AirConsole_20190627023151787.zip](https://github.com/armandoalonso/c3IDE/files/3332387/Psychokiller1888.for.N-Dream.AG_AirConsole_20190627023151787.zip)

**Comment by armandoalonso** [comment]
at some point there was breaking change to the way extra files were being treated. i added extra properties and instead of storing them in plain text, i store their bytes , since this, what you can do is go into the 3rd party file window check the box that say plain text and leave the window and save then try and compile again, i released a fix for a bug with the saving on that page.

**Comment by armandoalonso** [comment]
fixed the remaining known issues with the importer. you should be able to import the c3addon from scratch and it have compile successfully. fixed 3rd party file, and ace param naming convention, also fixed validation around language file.
