### ISSUE TITLE
PluginProperty "combo" format error

### ISSUE THREAD

**Issue by colludium** [armandoalonso/c3IDE#41]
Behavior.js Edit Time. Creating combo PluginProperty creates the following entry:

`new SDK.PluginProperty("combo", "test-property", {"items":["item1", "item2", "item3"]}, "initialValue": "item1")`

This will cause a crash because the items and initial value should be an Options Object:

`new SDK.PluginProperty("combo", "test-property", {"items":["item1", "item2", "item3"], "initialValue": "item1"})`

**Comment by armandoalonso** [comment]
yep fixing now, should have a fixed deployed in the next few min

**Comment by colludium** [comment]
Awesome IDE, by the way!!

**Comment by armandoalonso** [comment]
deployed fix, restart the app and it should prompt for update. thanks for the find. any other issue let me know

**Comment by colludium** [comment]
Awesome! Thank you.
