### ISSUE TITLE
Server reload

### ISSUE THREAD

**Issue by Armaldio** [armandoalonso/c3IDE#46]
Am I doing something wrong

1. Make changes 
2. Test C3 addon
3. Start editor
4. Load project
5. Test addon
6. Stop server
7. -> 1.

It's a bit tedious
A good thing could be to auto-reload addon when changes are made ?

**Comment by armandoalonso** [comment]
There is an compile on save feature which acts kinda like nodemon, when files change it will recompile the folder where c3 addon is being tested from. 

![image](https://user-images.githubusercontent.com/7579560/62466266-efd47d80-b75e-11e9-826b-47839420d7d9.png)

This does not reload the addon on c3. construct loads the addons when it starts, and uses a cached version, you would need to refresh c3 for the addon with the changes to load.

**Comment by Armaldio** [comment]
I get it, it's perfect 
At least it save me from starting and stopping the server!
Some options in here should be enabled by default :p

**Comment by armandoalonso** [comment]
okay coo, closing this issue, since it already exists
