### ISSUE TITLE
Compiled effect addon shows wrong version in Construct

### ISSUE THREAD

**Issue by kokolihapihvi** [armandoalonso/c3IDE#48]
Build number is ignored, and is replaced with revision number.

https://github.com/armandoalonso/c3IDE/blob/ae155a7d185ff7f74de9f50cde3695ff5b68c491/c3IDE/Compiler/AddonCompiler.cs#L564

**Comment by armandoalonso** [comment]
okay i see the typo i will get a fix out for this soon

**Comment by armandoalonso** [comment]
i just finished merging this fix in, when you update the app this should be fixed
