### ISSUE TITLE
Error importing c3addon, `same key`

### ISSUE THREAD

**Issue by MikalDev** [armandoalonso/c3IDE#51]
```
10/24/2019 9:39:31 PM : IMPORT => EXTRACTING C3RUNTIME / ACTIONS

10/24/2019 9:39:31 PM : IMPORT => EXTRACTING C3RUNTIME / CONDITION

10/24/2019 9:39:31 PM : IMPORT => EXTRACTING C3RUNTIME / EXPRESSIONS

10/24/2019 9:39:31 PM : IMPORT => ERROR -> 
An item with the same key has already been added.

10/24/2019 9:39:31 PM : IMPORT => TRACE -> 
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at c3IDE.Managers.C3AddonImporter.<>c__DisplayClass0_0.<Import>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at c3IDE.Managers.C3AddonImporter.<Import>d__0.MoveNext()
```

Importing this c3addon:
https://github.com/gritsenko/c3_spine_plugin/raw/master/dist/Spine-v1.3.0.c3addon

I don't see any duplicates, can the error thrown also share the key that is causing the error, so I can debug?

**Comment by armandoalonso** [comment]
okay the duplicate happens when looking at the third party files, there are 2 files with teh same name in different paths "spine-webgl.js" its inside the DomScript folder and the c3runtime folder, during the import i used only the file names as keys, which caused the error

**Comment by armandoalonso** [comment]
`
            // this._info.AddFileDependency({
            //     filename: "c3runtime/spine-webgl.js",
            //     type: "external-dom-script"
            // });

            this._info.SetDOMSideScripts(["c3runtime/spine-webgl.js"]);`

if you remove the comment area it will be a quick fix.

**Comment by armandoalonso** [comment]
so question is it possible to to assign the same file as both dom script & normal file dependency?

**Comment by armandoalonso** [comment]
I published a fix around those file names let me know how it goes! i will leave this issue open for now, and close later after some more testing

**Comment by MikalDev** [comment]
Thanks for the quick reply, this may be an addon error also. I’ll review what’s actually being used. I don’t imagine it’s actually being loaded twice.

**Comment by armandoalonso** [comment]
no its not being loaded twice the file dependency line is commented out, but when parsing the files i did not take that into account.

**Comment by MikalDev** [comment]
Got, thanks for the fix!
