### ISSUE TITLE
invalid amount of parameter placeholder

### ISSUE THREAD

**Issue by masscube** [armandoalonso/c3IDE#52]
I get always this message when i create on a empty new addon under actions a parameter:
Info => invalid amount of parameter placeholder in display text for test, 1 parameters expected 0 placeholders {#} in display text

Ace.json:
`{
  "id": "test",
  "scriptName": "Test",
  "highlight": false,
  "params": [
    {
      "id": "test",
      "type": "any",
      "initialValue": "test"
    }
  ]
}`

Language:
`"test": {
	"list-name": "Test",
	"display-text": "this is the display text",
	"description": "this is the description",
	"params": {
        "test": {
            "name": "Test",
            "desc": "test"
        }
    }
}`

Code
`Test(test)
{
	//implementation
}`

**Comment by armandoalonso** [comment]
That's expected behavior, c3 enforces you to provide placeholder in the display text setting for every parameter. The add-on will fail to load so I throw an error before you get that far. Just add {1} or {0} I can't remember if it's zero indexes, I would double check the documentation.
