### ISSUE TITLE
Bug importing a c3addon causing 3rd party script issues

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#55]
I imported this c3addon. Then, when I used the web server to try the addon out in C3, I get errors with it not importing properly 3rd party files.

The addon itself works when imported in C3 directly

[html-element-0.0.2.7-stable.zip](https://github.com/armandoalonso/c3IDE/files/4020728/html-element-0.0.2.7-stable.zip)

**Comment by armandoalonso** [comment]
i was able to reproduce the issue, it does not seem to be importing domSide.js, i will investigate this.

**Comment by armandoalonso** [comment]
updated new version, C3 no longer crashes for not finding the file, i will leave issue open, f the issue is resolved let me know and ill close it.

**Comment by skymen** [comment]
Ok, so initially, I thought there was an issue with the new version where the file was not on the server, but it turns out it was, but addon.json was not updated. Removing the cached folder from roaming/c3ide_data/server/test fixed the issue

**Comment by skymen** [comment]
However, I found a new issue, so I'll create a new issue for it

**Comment by skymen** [comment]
Never got this issue again, so closing
