### ISSUE TITLE
File seems to get modified when sent to the server and it breaks some code

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#56]
Same file as https://github.com/armandoalonso/c3IDE/issues/55 when previewed, an error occurs. It comes from a "const" operator not being in the right place.

This is the concerned piece of code:
(starting line 840 of instance.js in the IDE)
```JS
CreateElement() {
      const newEl = Dom.create(`<${this.html.tag} sa-uid=${this.html.uid}></${this.html.tag}>`);
      // const newEl = document.createElement(`${this.html.tag}`); //
      // newEl.setAttribute("sa-uid", `${this.html.uid}`);

      // inserisco l'elemento nella pagina
      Dom.append(Dom.findByTagName('body')[0], newEl);

      // seleziono l'elemento appena inserito
      this.SetEl();
```

However, this is the content of the file sent to the server 
(starting line 954)
```JS
CreateElement()
        {
            const newEl = Dom.create(` < $
            {
                this.html.tag
            }
            sa - uid = $
            {
                this.html.uid
            } > < /${this.html.tag}>`);
      / / const newEl = document.createElement(`$
            {
                this.html.tag
            }`); //
            // newEl.setAttribute("sa-uid", `${this.html.uid}`);

            // inserisco l'elemento nella pagina
            Dom.append(Dom.findByTagName('body')[0], newEl);

            // seleziono l'elemento appena inserito
            this.SetEl();
```

As you can see, the content of the file was modified, and some code that was commented was uncommented and broke the addon.
I wonder why the content of the file is even modified when going from IDE to exported version 🤔

**Comment by armandoalonso** [comment]
ahh its the template syntax, apparently the js formatter i use does not understand it, i will disbale the formatting on export and it find an alternative, i can also add an option to format on export

**Comment by armandoalonso** [comment]
i have added an option to disable the formatting on export in the next build which should solve this issue
