### ISSUE TITLE
JS literals and comments sometimes get wrongly expanded on export

### ISSUE THREAD

**Issue by skymen** [armandoalonso/c3IDE#61]
Upon exporting the addon, it seems like the JS files go through something that beautifies the code, but it messes up with JS literals (`strings with ${backquotes} in them`) if they also happen to have brackets in them, which happens all the time.

It expands them, and it breaks the code most of the time, so the issue doesn't appear in dev mode, but it does after export.

While I should tell you to fix it, I'd actually rather you disabled that beautifying entirely. I prefer being 100% sure my code is exactly the same after I export it to avoid these kinds of issues.

**Comment by armandoalonso** [comment]
adding option to disable code formatting on export for next release
