### ISSUE TITLE
JSON editor for language (custom category)?

### ISSUE THREAD

**Issue by giangledev** [armandoalonso/c3IDE#68]
Hi,

I could not find where I add language text for Action's custom category. So each time after publishing, I need to unzip the addon then edit the language file.

What I mean is that can we make a location in IDE, so we can edit language file as below

```
"aceCategories": {
   "custom": "Custom"
},
```

Br,

**Comment by skymen** [comment]
![image](https://user-images.githubusercontent.com/11213825/132939515-899d15b6-9f18-413e-8d1f-7de74092078b.png)
![image](https://user-images.githubusercontent.com/11213825/132939518-d854cd17-45f8-4be6-b697-42ab8a06a8eb.png)

Is this what you mean?

**Comment by giangledev** [comment]
> ![image](https://user-images.githubusercontent.com/11213825/132939515-899d15b6-9f18-413e-8d1f-7de74092078b.png)
> ![image](https://user-images.githubusercontent.com/11213825/132939518-d854cd17-45f8-4be6-b697-42ab8a06a8eb.png)
> 
> Is this what you mean?

Thank you! Sorry that's my bad, not checking carefully!

Really great tool! Many thanks!
