### ISSUE TITLE
Ability to open .c3ide from the explorer

### ISSUE THREAD

**Issue by Armaldio** [armandoalonso/c3IDE#8]
Could be great to double click a .c3ide file so automatically open the editor with the addon loaded

**Comment by armandoalonso** [comment]
Yes I agree I will make this happen.

**Comment by armandoalonso** [comment]
okay figured out the issue, the path that was being returned in the argument when double clicking the .c3ide file, was actually a uri. after converting the uri to a local path everything should be working as expected in the latest build. you can now double click the .c3ide export and it should open up the app with the correct addon loaded.

**Comment by armandoalonso** [comment]
this behaves differently than dragging the .c3ide file into the project, when you drag it it it duplicates the addon. but opening the file will overwrite the addon with the contents of the file. and then open that file. if this behavior becomes a problem i will change to to behave the same and duplicate the addon.
